_commit: v1.12.1-1-g902fdaa
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: external-dns
helmRelease: external-dns-cloudflare
helmRepo: https://kubernetes-sigs.github.io/external-dns/
helmValues: helm/values.yaml
helmVersion: ''
homepageEnabled: false
ingress: false
labels: |-
  app.kubernetes.io/instance: external-dns-cloudflare
  app.kubernetes.io/name: cloudflare
name: external-dns-cloudflare
namespace: external-dns-cloudflare
pvc: false
reloader: true
resources:
- external-secrets.yaml
service: false
serviceAccount: false
upstreamURL: https://github.com/kubernetes-sigs/external-dns
url: https://github.com/charlesthomas/homelab-external-dns-cloudflare
