_commit: v1.12.1-10-g6796849
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: |-
  app.kubernetes.io/instance: external-dns-cloudflare
  app.kubernetes.io/name: cloudflare
name: external-dns-cloudflare
namespace: external-dns-cloudflare
pvc: false
reloader: true
resources:
- deployments.yaml
- external-secrets.yaml
- rbac.yaml
- service-accounts.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://github.com/kubernetes-sigs/external-dns
url: https://github.com/charlesthomas/homelab-external-dns-cloudflare
