---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns-cloudflare

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-external-dns-cloudflare
commonLabels:
  app.kubernetes.io/instance: external-dns-cloudflare
  app.kubernetes.io/name: cloudflare

resources:
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
- resources/services.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: external-dns-cloudflare
      namespace: external-dns-cloudflare
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
