---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns-cloudflare

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-external-dns-cloudflare
commonLabels:
  app.kubernetes.io/instance: external-dns-cloudflare
  app.kubernetes.io/name: cloudflare

resources:
- resources/external-secrets.yaml
- resources/namespaces.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: external-dns-cloudflare
      namespace: external-dns-cloudflare
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
helmCharts:
- name: external-dns
  namespace: external-dns-cloudflare
  releaseName: external-dns-cloudflare
  repo: https://kubernetes-sigs.github.io/external-dns/
  valuesFile: helm/values.yaml
