---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: external-dns-cloudflare
spec:
  target:
    name: cloudflare
    deletionPolicy: Delete
  data:
    - secretKey: api-key
      remoteRef:
        key: add0d418-949a-4bda-b535-52055706665e
        property: api-key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
