---
apiVersion: v1
automountServiceAccountToken: null
kind: ServiceAccount
metadata:
  annotations:
    repo: https://github.com/charlesthomas/homelab-external-dns-cloudflare
  labels:
    app.kubernetes.io/instance: external-dns-cloudflare
    app.kubernetes.io/name: cloudflare
  name: external-dns-cloudflare
  namespace: external-dns-cloudflare
