---
apiVersion: v1
kind: Service
metadata:
  annotations:
    repo: https://github.com/charlesthomas/homelab-external-dns-cloudflare
  labels:
    app.kubernetes.io/instance: external-dns-cloudflare
    app.kubernetes.io/name: cloudflare
  name: external-dns-cloudflare
  namespace: external-dns-cloudflare
spec:
  ports:
    - name: http
      port: 7979
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: external-dns-cloudflare
    app.kubernetes.io/name: cloudflare
  type: ClusterIP
